[toolchain]

[features]
seeds = true

[programs.localnet]
x402_scoring = "11111111111111111111111111111111"

[programs.devnet]
x402_scoring = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
demo = "npx ts-node scripts/demo.ts"

[test]
startup_wait = 20000
